# Generated by Django 3.2.2 on 2021-05-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_project_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='complete',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('N', 'Not Started'), ('I', 'In Progress'), ('C', 'Completed')], default='N', max_length=1),
        ),
    ]
