# Generated by Django 3.2.2 on 2021-05-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210510_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='toolPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tool')),
            ],
        ),
    ]
