# Generated by Django 3.2.2 on 2021-05-11 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210511_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='image',
        ),
        migrations.CreateModel(
            name='MaterialPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.material')),
            ],
        ),
    ]
