# Generated by Django 3.2.2 on 2021-05-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210511_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='image',
        ),
    ]
